// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Model;
using System;

namespace letsaddmonadic.Migrations
{
    [DbContext(typeof(AgendaContext))]
    partial class AgendaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("Model.MyTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("TascollId");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("TascollId");

                    b.ToTable("MyTask");
                });

            modelBuilder.Entity("Model.Tascoll", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Tascoll");
                });

            modelBuilder.Entity("Model.Urgent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("TascollId");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("TascollId");

                    b.ToTable("Urgent");
                });

            modelBuilder.Entity("Model.MyTask", b =>
                {
                    b.HasOne("Model.Tascoll")
                        .WithMany("Inner")
                        .HasForeignKey("TascollId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Model.Urgent", b =>
                {
                    b.HasOne("Model.Tascoll")
                        .WithMany("UrgInner")
                        .HasForeignKey("TascollId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
